services:
  geovault-server:
    build: .
    command: gunicorn geovault.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geodb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - staticfiles:/geovault/staticfiles
      - mediafiles:/geovault/mediafiles
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    hostname: geovault-nginx
    image: docker.io/nginx:stable
    # build:
    #   context: "./nginx"
    volumes:
      - ./data:/dkdata
      - ./nginx/conf:/nginxfiles/conf
      - staticfiles:/geovault/staticfiles
      - mediafiles:/geovault/mediafiles
    ports:
      - "80:7000"
    environment:
      NGINX_SITE: local

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
