# Generated by Django 5.2 on 2025-04-13 01:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import geodata.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="raw_files/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("SHP", "Shapefile"),
                            ("GPKG", "GeoPackage"),
                            ("KML", "KML"),
                            ("GEOJSON", "GeoJSON"),
                            ("CSV", "CSV"),
                            ("XLSX", "Excel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("geometry", django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "farmers",
                    models.ManyToManyField(
                        limit_choices_to=geodata.models.get_farmer_users_query,
                        related_name="related_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_data",
                        to="geodata.rawfile",
                    ),
                ),
            ],
        ),
    ]
